// <auto-generated />
namespace Bauhaus.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class shiptmentToLong : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(shiptmentToLong));
        
        string IMigrationMetadata.Id
        {
            get { return "201309122001383_shiptmentToLong"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
