// <auto-generated />
namespace Bauhaus.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class TrimReportsComments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TrimReportsComments));
        
        string IMigrationMetadata.Id
        {
            get { return "201308052031131_TrimReportsComments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
